{
 "title": "ML service dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ModelType", "query": "lr,cb" },
   { "name": "gender", "query": "f,m" }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Error rate')",
     "targetFull": "alias(divideSeries(movingAverage(aliasByNode(stats.ml_service.predict_gender.request_status.error.count, -2), '1min'), movingAverage(sumSeries(aliasByNode(stats.ml_service.predict_gender.request_status.*.count, -2)), '1min')), 'Error rate')"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(sumSeries(aliasByNode(stats.ml_service.predict_gender.request_status.*.count, -2)), 60)"
    }
   ]
  },
  { "title": "Probas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Probas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.ml_service.predict_gender.$ModelType.result.$gender.proba, -4, -2)"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Feature Extraction Timing (90 perc)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(scale(stats.timers.ml_service.predict_gender.$ModelType.timing.feature_extraction.upper_90, 1000), -4)"
    }
   ]
  },
  {
   "title": "Model Inference Timing (90 perc)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(scale(stats.timers.ml_service.predict_gender.$ModelType.timing.model_inference.upper_90, 1000), -4)"
    }
   ]
  },
  {
   "title": "Service Response Timing – Latency (90 perc)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(scale(stats.timers.ml_service.predict_gender.$ModelType.timing.service_resp.upper_90, 1000), -4)"
    }
   ]
  },
  {
   "title": "Service Response Timing (mean)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(scale(stats.timers.ml_service.predict_gender.$ModelType.timing.service_resp.mean, 1000), -4)"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Error rate')",
     "targetFull": "alias(divideSeries(movingAverage(aliasByNode(stats.ml_service.predict_gender.request_status.error.count, -2), '1min'), movingAverage(sumSeries(aliasByNode(stats.ml_service.predict_gender.request_status.*.count, -2)), '1min')), 'Error rate')"
    }
   ]
  },
  {
   "title": "Prediction Male Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "alias(divideSeries(#A, #B), 'Male Rate')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(aliasByNode(stats.ml_service.predict_gender.$ModelType.result.m.count, -2)), '5min'), movingAverage(sumSeries(aliasByNode(stats.ml_service.predict_gender.$ModelType.result.*.count, -2)), '5min')), 'Male Rate')"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "refCount": -1,
     "target": "aliasByNode(carbon.agents.6bcdac83a2de-a.cpuUsage, -2)"
    }
   ]
  }
 ]
}